// API CALLS
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";

// COUNTRIES
export const LOAD_COUNTRIES_SUCCESS = "LOAD_COUNTRIES_SUCCESS";
export const LOAD_SELECTED_COUNTRIES = "LOAD_SELECTED_COUNTRIES";
export const LOAD_COUNTRY_CODE = "LOAD_COUNTRY_CODE";

// HISTORY
export const LOAD_HISTORY_SUCCESS = "LOAD_HISTORY_SUCCESS";
export const NO_CASES_FOUND = "NO_CASES_FOUND";
export const LOAD_STATISTICS_SUCCESS = "LOAD_STATISTICS_SUCCESS";
export const LOAD_DAILY_CASES = "LOAD_DAILY_CASES";
